CREATE TABLE IF NOT EXISTS students(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  firstname VARCHAR(25) NOT NULL,
  lastname VARCHAR(25) NOT NULL,
  cohort_id INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS cohorts(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(25) NOT NULL
);
CREATE TABLE IF NOT EXISTS studentcohort(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  student_id INTEGER NOT NULL,
  cohort_id INTEGER NOT NULL,
  FOREIGN KEY student_id REFERENCES students(id) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY cohort_id REFERENCES cohorts(id) ON UPDATE CASCADE ON DELETE CASCADE
);
