CREATE TABLE IF NOT EXISTS STUDENT(
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  FIRST_NAME VARCHAR(100),
  LAST_NAME VARCHAR(100),
  COHORT_ID VARCHAR(1),
  FOREIGN KEY (COHORT_ID) REFERENCES COHORT(ID)
);
CREATE TABLE IF NOT EXISTS COHORT(
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  COHORT_NAME VARCHAR(100)
);
--INSERT INTO STUDENT (FIRST_NAME,LAST_NAME) VALUES('ARI','ADIPRANA',1);
